#pragma once

#if NEUTRINO_NEPOSTPROCESSOR_BUILD
#define NEFEXP_NEPOSTPROCESSOR Q_DECL_EXPORT
#define NECEXP_NEPOSTPROCESSOR  Q_DECL_EXPORT
#else
#define NEFEXP_NEPOSTPROCESSOR  Q_DECL_IMPORT
#define NECEXP_NEPOSTPROCESSOR  Q_DECL_IMPORT
#endif

