#pragma once

#if NEUTRINO_NEUIPROPERTIES_BUILD
#define NEFEXP_NEUIPROPERTIES Q_DECL_EXPORT
#define NECEXP_NEUIPROPERTIES Q_DECL_EXPORT
#else
#define NEFEXP_NEUIPROPERTIES Q_DECL_IMPORT
#define NECEXP_NEUIPROPERTIES Q_DECL_IMPORT
#endif

