#pragma once

#if FDYN_PLUGINS_BUILD
#define FDYNFEXP_PLUGINS Q_DECL_EXPORT
#define FDYNCEXP_PLUGINS Q_DECL_EXPORT
#else
#define FDYNFEXP_PLUGINS Q_DECL_IMPORT
#define FDYNCEXP_PLUGINS Q_DECL_IMPORT
#endif

