#pragma once

#if NEUTRINO_NEUIUTILITIES_BUILD
#define NEFEXP_NEUIUTILITIES Q_DECL_EXPORT
#define NECEXP_NEUIUTILITIES Q_DECL_EXPORT
#else
#define NEFEXP_NEUIUTILITIES Q_DECL_IMPORT
#define NECEXP_NEUIUTILITIES Q_DECL_IMPORT
#endif

